### PR TITLE
Fix issue #60 with 'unknown column projects.status' and CSV export problem

### PR DESCRIPTION
**Pull request by SashaH**

### CODE REVIEW

**Comment by rubetron** [comment]
About the csv export method, you need to add a condition when the date_from / date_to are empty. This happens when you select "all" in the period's select input.
It will return date_from=Timesheet[date_from].

I was making changes but i can find the solution because @timesheet dont return the period attribute value .

Beside this little problem, works like a charm. Thanks

**Comment by VVD** [comment]
SashaH, can you commit changes to master branch?
Or you can just fork it and fix all these bugs.

**Comment by SashaH** [comment]
VVD, I can work only in my fork.

**Comment by VVD** [comment]
SashaH, can't find your fork: https://github.com/p-h-i-l/redmine_timesheet_plugin/network/members

**Comment by alxwr** [comment]
@VVD
fwiw: the fork is here: https://github.com/speedandfunction/redmine_timesheet_plugin

**Pull request closed without merging**
